"""add profile versions and evidence

Revision ID: 1ddb543ec69b
Revises: 603a60d0b4ba
Create Date: 2026-07-29 21:36:07.661025

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '1ddb543ec69b'
down_revision = '603a60d0b4ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'version', name='uq_profile_version_user_version')
    )
    with op.batch_alter_table('profile_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_versions_user_id'), ['user_id'], unique=False)

    op.create_table('profile_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_version_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=80), nullable=False),
    sa.Column('old_value_json', sa.JSON(), nullable=True),
    sa.Column('new_value_json', sa.JSON(), nullable=True),
    sa.Column('evidence_type', sa.String(length=40), nullable=False),
    sa.Column('evidence_source_id', sa.String(length=120), nullable=True),
    sa.Column('evidence_description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("evidence_type IN ('dialogue','assessment','question_error','tutor_session','learning_behavior','resource_feedback','migration_snapshot')", name='ck_profile_evidence_type'),
    sa.ForeignKeyConstraint(['profile_version_id'], ['profile_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_evidence_profile_version_id'), ['profile_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_evidence_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_resource_types', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('weekly_time_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('practice_level', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('current_version_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_profiles_current_version_id'), ['current_version_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_profiles_current_version_id',
            'profile_versions',
            ['current_version_id'],
            ['id'],
            ondelete='SET NULL',
        )

    _backfill_profile_versions()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_profiles_current_version_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_profiles_current_version_id'))
        batch_op.drop_column('current_version_id')
        batch_op.drop_column('practice_level')
        batch_op.drop_column('weekly_time_minutes')
        batch_op.drop_column('preferred_resource_types')

    with op.batch_alter_table('profile_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_evidence_user_id'))
        batch_op.drop_index(batch_op.f('ix_profile_evidence_profile_version_id'))

    op.drop_table('profile_evidence')
    with op.batch_alter_table('profile_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_versions_user_id'))

    op.drop_table('profile_versions')
    # ### end Alembic commands ###


def _backfill_profile_versions():
    """把当前画像保存为真实 v1 快照，不伪造历史变化。"""
    bind = op.get_bind()
    profiles = sa.table(
        'profiles',
        sa.column('id', sa.Integer),
        sa.column('user_id', sa.Integer),
        sa.column('topic', sa.String),
        sa.column('major', sa.String),
        sa.column('knowledge_level', sa.String),
        sa.column('learning_goal', sa.Text),
        sa.column('learning_style', sa.String),
        sa.column('cognitive_preference', sa.String),
        sa.column('prior_experience', sa.Text),
        sa.column('time_availability', sa.String),
        sa.column('motivation_driver', sa.String),
        sa.column('engagement_pattern', sa.String),
        sa.column('weak_points', sa.Text),
        sa.column('preferred_resource_types', sa.JSON),
        sa.column('weekly_time_minutes', sa.Integer),
        sa.column('practice_level', sa.String),
        sa.column('current_version_id', sa.Integer),
        sa.column('updated_at', sa.DateTime),
    )
    profile_versions = sa.table(
        'profile_versions',
        sa.column('id', sa.Integer),
        sa.column('user_id', sa.Integer),
        sa.column('version', sa.Integer),
        sa.column('snapshot_json', sa.JSON),
        sa.column('change_summary', sa.Text),
        sa.column('created_at', sa.DateTime),
    )
    profile_evidence = sa.table(
        'profile_evidence',
        sa.column('user_id', sa.Integer),
        sa.column('profile_version_id', sa.Integer),
        sa.column('dimension', sa.String),
        sa.column('old_value_json', sa.JSON),
        sa.column('new_value_json', sa.JSON),
        sa.column('evidence_type', sa.String),
        sa.column('evidence_source_id', sa.String),
        sa.column('evidence_description', sa.Text),
        sa.column('confidence', sa.Float),
        sa.column('created_at', sa.DateTime),
    )

    rows = bind.execute(sa.select(profiles)).mappings().all()
    for row in rows:
        preferred_resource_types = row['preferred_resource_types'] or []
        practice_level = row['practice_level'] or 'beginner'
        snapshot = {
            'topic': row['topic'] or '',
            'major': row['major'] or '',
            'knowledge_level': row['knowledge_level'] or 'beginner',
            'learning_goal': row['learning_goal'] or '',
            'learning_style': row['learning_style'] or 'mixed',
            'cognitive_preference': row['cognitive_preference'] or '',
            'prior_experience': row['prior_experience'] or '',
            'time_availability': row['time_availability'] or '',
            'motivation_driver': row['motivation_driver'] or '',
            'engagement_pattern': row['engagement_pattern'] or '',
            'weak_points': row['weak_points'] or '',
            'preferred_resource_types': preferred_resource_types,
            'weekly_time_minutes': row['weekly_time_minutes'],
            'practice_level': practice_level,
        }
        created_at = row['updated_at'] or datetime.now()
        result = bind.execute(
            profile_versions.insert().values(
                user_id=row['user_id'],
                version=1,
                snapshot_json=snapshot,
                change_summary='迁移现有画像为初始真实快照',
                created_at=created_at,
            )
        )
        version_id = result.lastrowid
        if not version_id:
            version_id = bind.execute(
                sa.select(sa.func.max(profile_versions.c.id))
                .where(profile_versions.c.user_id == row['user_id'])
            ).scalar_one()
        bind.execute(
            profile_evidence.insert().values(
                user_id=row['user_id'],
                profile_version_id=version_id,
                dimension='profile_snapshot',
                old_value_json=None,
                new_value_json=snapshot,
                evidence_type='migration_snapshot',
                evidence_source_id=f"profile:{row['id']}",
                evidence_description='数据库迁移时保存的当前画像；不代表更早的历史版本。',
                confidence=1.0,
                created_at=created_at,
            )
        )
        bind.execute(
            profiles.update()
            .where(profiles.c.id == row['id'])
            .values(
                preferred_resource_types=preferred_resource_types,
                practice_level=practice_level,
                current_version_id=version_id,
            )
        )
