"""add p2 cognitive depth and teaching strategy

Revision ID: 29fc207451cc
Revises: c4a7d9e28f31
Create Date: 2026-07-30 14:02:32.272081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29fc207451cc'
down_revision = 'c4a7d9e28f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_events', schema=None) as batch_op:
        batch_op.drop_constraint(
            'ck_learning_event_type',
            type_='check',
        )
        batch_op.create_check_constraint(
            'ck_learning_event_type',
            "event_type IN ("
            "'question_correct','question_wrong','question_partial',"
            "'assessment_complete','hint_request','resource_open',"
            "'resource_complete','node_open','node_complete','code_run',"
            "'code_error','tutor_help','replan_trigger',"
            "'learning_block_detected'"
            ")",
        )

    with op.batch_alter_table('adaptive_exams', schema=None) as batch_op:
        batch_op.drop_constraint(
            'ck_adaptive_exam_goal',
            type_='check',
        )
        batch_op.create_check_constraint(
            'ck_adaptive_exam_goal',
            "goal IN ("
            "'diagnosis','reinforcement','mock','comprehensive','transfer'"
            ")",
        )

    op.create_table('teaching_strategy_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_type', sa.String(length=60), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('average_observed_gain', sa.Float(), nullable=False),
    sa.Column('gain_variance', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('stability', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'strategy_type', name='uq_teaching_strategy_stat')
    )
    with op.batch_alter_table('teaching_strategy_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teaching_strategy_stats_strategy_type'), ['strategy_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_strategy_stats_user_id'), ['user_id'], unique=False)

    op.create_table('cognitive_diagnoses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=120), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=True),
    sa.Column('first_error_step', sa.Integer(), nullable=True),
    sa.Column('root_cause_knowledge_point_id', sa.Integer(), nullable=True),
    sa.Column('overall_status', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('propagation_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("overall_status IN ('no_error','root_error','insufficient_evidence')", name='ck_cognitive_diagnosis_status'),
    sa.ForeignKeyConstraint(['assessment_id'], ['quiz_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['root_cause_knowledge_point_id'], ['knowledge_points.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'assessment_id', 'question_id', name='uq_cognitive_diagnosis_question')
    )
    with op.batch_alter_table('cognitive_diagnoses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cognitive_diagnoses_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cognitive_diagnoses_knowledge_point_id'), ['knowledge_point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cognitive_diagnoses_root_cause_knowledge_point_id'), ['root_cause_knowledge_point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cognitive_diagnoses_user_id'), ['user_id'], unique=False)

    op.create_table('mastery_dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=50), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('last_assessment_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("dimension IN ('conceptual_understanding','procedural_application','reasoning','coding','transfer')", name='ck_mastery_dimension_type'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_assessment_id'], ['quiz_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'knowledge_point_id', 'dimension', name='uq_mastery_dimension')
    )
    with op.batch_alter_table('mastery_dimensions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mastery_dimensions_dimension'), ['dimension'], unique=False)
        batch_op.create_index(batch_op.f('ix_mastery_dimensions_knowledge_point_id'), ['knowledge_point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mastery_dimensions_last_assessment_id'), ['last_assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mastery_dimensions_user_id'), ['user_id'], unique=False)

    op.create_table('misconceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('correction_strategy', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'code', name='uq_misconception_course_code')
    )
    with op.batch_alter_table('misconceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_misconceptions_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_misconceptions_knowledge_point_id'), ['knowledge_point_id'], unique=False)

    op.create_table('self_confidence_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=120), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=True),
    sa.Column('self_confidence', sa.Integer(), nullable=False),
    sa.Column('actual_score', sa.Float(), nullable=False),
    sa.Column('calibration_signal', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("calibration_signal IN ('calibrated','overconfidence','underconfidence','insufficient')", name='ck_self_confidence_signal'),
    sa.ForeignKeyConstraint(['assessment_id'], ['quiz_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'assessment_id', 'question_id', name='uq_self_confidence_question')
    )
    with op.batch_alter_table('self_confidence_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_self_confidence_records_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_self_confidence_records_knowledge_point_id'), ['knowledge_point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_self_confidence_records_user_id'), ['user_id'], unique=False)

    op.create_table('teaching_strategy_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('strategy_type', sa.String(length=60), nullable=False),
    sa.Column('previous_strategy_type', sa.String(length=60), nullable=True),
    sa.Column('reason_codes_json', sa.JSON(), nullable=True),
    sa.Column('actions_json', sa.JSON(), nullable=True),
    sa.Column('input_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('switched', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assessment_id'], ['quiz_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teaching_strategy_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teaching_strategy_decisions_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_strategy_decisions_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_strategy_decisions_knowledge_point_id'), ['knowledge_point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_strategy_decisions_strategy_type'), ['strategy_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_strategy_decisions_user_id'), ['user_id'], unique=False)

    op.create_table('transfer_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('adaptive_exam_id', sa.Integer(), nullable=True),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('levels_json', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('capability_state', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('ready','completed')", name='ck_transfer_assessment_status'),
    sa.ForeignKeyConstraint(['adaptive_exam_id'], ['adaptive_exams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_id'], ['quiz_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'result_id', 'knowledge_point_id', name='uq_transfer_assessment_result_point')
    )
    with op.batch_alter_table('transfer_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_assessments_adaptive_exam_id'), ['adaptive_exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfer_assessments_knowledge_point_id'), ['knowledge_point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfer_assessments_result_id'), ['result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfer_assessments_user_id'), ['user_id'], unique=False)

    op.create_table('cognitive_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=True),
    sa.Column('concept', sa.String(length=180), nullable=True),
    sa.Column('expected_text', sa.Text(), nullable=True),
    sa.Column('student_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_role', sa.String(length=30), nullable=False),
    sa.Column('error_type', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('course_sources_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("error_role IN ('none','root_error','derived_error','independent_error','uncertain')", name='ck_cognitive_step_error_role'),
    sa.CheckConstraint("status IN ('correct','incorrect','uncertain','not_observed')", name='ck_cognitive_step_status'),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['cognitive_diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnosis_id', 'step_index', name='uq_cognitive_step_index')
    )
    with op.batch_alter_table('cognitive_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cognitive_steps_diagnosis_id'), ['diagnosis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cognitive_steps_knowledge_point_id'), ['knowledge_point_id'], unique=False)

    op.create_table('user_misconceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('misconception_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(), nullable=False),
    sa.Column('last_detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('suspected','confirmed','improving','resolved')", name='ck_user_misconception_status'),
    sa.ForeignKeyConstraint(['misconception_id'], ['misconceptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'misconception_id', name='uq_user_misconception')
    )
    with op.batch_alter_table('user_misconceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_misconceptions_misconception_id'), ['misconception_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_misconceptions_user_id'), ['user_id'], unique=False)

    op.create_table('misconception_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_misconception_id', sa.Integer(), nullable=False),
    sa.Column('cognitive_step_id', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source_type IN ('question_wrong','reasoning_step','assessment','tutor_response','hint_request','code_error','transfer_question','correct_response')", name='ck_misconception_evidence_type'),
    sa.ForeignKeyConstraint(['assessment_id'], ['quiz_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cognitive_step_id'], ['cognitive_steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_misconception_id'], ['user_misconceptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_misconception_id', 'source_type', 'source_id', name='uq_misconception_evidence_source')
    )
    with op.batch_alter_table('misconception_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_misconception_evidence_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_misconception_evidence_cognitive_step_id'), ['cognitive_step_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_misconception_evidence_user_misconception_id'), ['user_misconception_id'], unique=False)

    op.create_table('teaching_interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('strategy_decision_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('path_node_id', sa.Integer(), nullable=True),
    sa.Column('path_version_id', sa.Integer(), nullable=True),
    sa.Column('trigger_event_id', sa.Integer(), nullable=True),
    sa.Column('assessment_before', sa.Integer(), nullable=True),
    sa.Column('assessment_after', sa.Integer(), nullable=True),
    sa.Column('strategy_type', sa.String(length=60), nullable=False),
    sa.Column('block_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('mastery_before', sa.Float(), nullable=True),
    sa.Column('mastery_after', sa.Float(), nullable=True),
    sa.Column('confidence_before', sa.Float(), nullable=True),
    sa.Column('confidence_after', sa.Float(), nullable=True),
    sa.Column('observed_gain', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("block_type IN ('KNOWLEDGE_GAP','MISCONCEPTION','PROCESS_ERROR','REPEATED_FAILURE','TRANSFER_FAILURE','INSUFFICIENT_EVIDENCE')", name='ck_teaching_intervention_block_type'),
    sa.CheckConstraint("status IN ('active','completed','cancelled')", name='ck_teaching_intervention_status'),
    sa.ForeignKeyConstraint(['assessment_after'], ['quiz_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assessment_before'], ['quiz_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_node_id'], ['learning_path_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['path_version_id'], ['learning_path_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_decision_id'], ['teaching_strategy_decisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trigger_event_id'], ['learning_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teaching_interventions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teaching_interventions_assessment_after'), ['assessment_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_interventions_assessment_before'), ['assessment_before'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_interventions_knowledge_point_id'), ['knowledge_point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_interventions_path_node_id'), ['path_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_interventions_path_version_id'), ['path_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_interventions_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_interventions_strategy_decision_id'), ['strategy_decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_interventions_trigger_event_id'), ['trigger_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teaching_interventions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_interventions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teaching_interventions_user_id'))
        batch_op.drop_index(batch_op.f('ix_teaching_interventions_trigger_event_id'))
        batch_op.drop_index(batch_op.f('ix_teaching_interventions_strategy_decision_id'))
        batch_op.drop_index(batch_op.f('ix_teaching_interventions_resource_id'))
        batch_op.drop_index(batch_op.f('ix_teaching_interventions_path_version_id'))
        batch_op.drop_index(batch_op.f('ix_teaching_interventions_path_node_id'))
        batch_op.drop_index(batch_op.f('ix_teaching_interventions_knowledge_point_id'))
        batch_op.drop_index(batch_op.f('ix_teaching_interventions_assessment_before'))
        batch_op.drop_index(batch_op.f('ix_teaching_interventions_assessment_after'))

    op.drop_table('teaching_interventions')
    with op.batch_alter_table('misconception_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_misconception_evidence_user_misconception_id'))
        batch_op.drop_index(batch_op.f('ix_misconception_evidence_cognitive_step_id'))
        batch_op.drop_index(batch_op.f('ix_misconception_evidence_assessment_id'))

    op.drop_table('misconception_evidence')
    with op.batch_alter_table('user_misconceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_misconceptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_misconceptions_misconception_id'))

    op.drop_table('user_misconceptions')
    with op.batch_alter_table('cognitive_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cognitive_steps_knowledge_point_id'))
        batch_op.drop_index(batch_op.f('ix_cognitive_steps_diagnosis_id'))

    op.drop_table('cognitive_steps')
    with op.batch_alter_table('transfer_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_assessments_user_id'))
        batch_op.drop_index(batch_op.f('ix_transfer_assessments_result_id'))
        batch_op.drop_index(batch_op.f('ix_transfer_assessments_knowledge_point_id'))
        batch_op.drop_index(batch_op.f('ix_transfer_assessments_adaptive_exam_id'))

    op.drop_table('transfer_assessments')
    with op.batch_alter_table('teaching_strategy_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teaching_strategy_decisions_user_id'))
        batch_op.drop_index(batch_op.f('ix_teaching_strategy_decisions_strategy_type'))
        batch_op.drop_index(batch_op.f('ix_teaching_strategy_decisions_knowledge_point_id'))
        batch_op.drop_index(batch_op.f('ix_teaching_strategy_decisions_assessment_id'))
        batch_op.drop_index(batch_op.f('ix_teaching_strategy_decisions_agent_run_id'))

    op.drop_table('teaching_strategy_decisions')
    with op.batch_alter_table('self_confidence_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_self_confidence_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_self_confidence_records_knowledge_point_id'))
        batch_op.drop_index(batch_op.f('ix_self_confidence_records_assessment_id'))

    op.drop_table('self_confidence_records')
    with op.batch_alter_table('misconceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_misconceptions_knowledge_point_id'))
        batch_op.drop_index(batch_op.f('ix_misconceptions_course_id'))

    op.drop_table('misconceptions')
    with op.batch_alter_table('mastery_dimensions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mastery_dimensions_user_id'))
        batch_op.drop_index(batch_op.f('ix_mastery_dimensions_last_assessment_id'))
        batch_op.drop_index(batch_op.f('ix_mastery_dimensions_knowledge_point_id'))
        batch_op.drop_index(batch_op.f('ix_mastery_dimensions_dimension'))

    op.drop_table('mastery_dimensions')
    with op.batch_alter_table('cognitive_diagnoses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cognitive_diagnoses_user_id'))
        batch_op.drop_index(batch_op.f('ix_cognitive_diagnoses_root_cause_knowledge_point_id'))
        batch_op.drop_index(batch_op.f('ix_cognitive_diagnoses_knowledge_point_id'))
        batch_op.drop_index(batch_op.f('ix_cognitive_diagnoses_assessment_id'))

    op.drop_table('cognitive_diagnoses')
    with op.batch_alter_table('teaching_strategy_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teaching_strategy_stats_user_id'))
        batch_op.drop_index(batch_op.f('ix_teaching_strategy_stats_strategy_type'))

    op.drop_table('teaching_strategy_stats')
    op.execute(
        "UPDATE adaptive_exams SET goal='comprehensive' "
        "WHERE goal='transfer'"
    )
    with op.batch_alter_table('adaptive_exams', schema=None) as batch_op:
        batch_op.drop_constraint(
            'ck_adaptive_exam_goal',
            type_='check',
        )
        batch_op.create_check_constraint(
            'ck_adaptive_exam_goal',
            "goal IN ("
            "'diagnosis','reinforcement','mock','comprehensive'"
            ")",
        )

    op.execute(
        "UPDATE learning_events SET event_type='replan_trigger' "
        "WHERE event_type='learning_block_detected'"
    )
    with op.batch_alter_table('learning_events', schema=None) as batch_op:
        batch_op.drop_constraint(
            'ck_learning_event_type',
            type_='check',
        )
        batch_op.create_check_constraint(
            'ck_learning_event_type',
            "event_type IN ("
            "'question_correct','question_wrong','question_partial',"
            "'assessment_complete','hint_request','resource_open',"
            "'resource_complete','node_open','node_complete','code_run',"
            "'code_error','tutor_help','replan_trigger'"
            ")",
        )
    # ### end Alembic commands ###
