"""add course knowledge structure

Revision ID: 603a60d0b4ba
Revises: 900e17ba0f92
Create Date: 2026-07-29 21:07:20.059881

"""
import hashlib
import json
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603a60d0b4ba'
down_revision = '900e17ba0f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_coverage', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_code'), ['code'], unique=True)

    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('chapter_order', sa.Integer(), nullable=False),
    sa.Column('start_page', sa.Integer(), nullable=True),
    sa.Column('end_page', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'chapter_order', name='uq_chapter_course_order')
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapters_course_id'), ['course_id'], unique=False)

    op.create_table('knowledge_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=30), nullable=False),
    sa.Column('learning_objectives_json', sa.JSON(), nullable=True),
    sa.Column('aliases_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'code', name='uq_knowledge_point_course_code')
    )
    with op.batch_alter_table('knowledge_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_points_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_points_course_id'), ['course_id'], unique=False)

    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=180), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('vector_ref', sa.String(length=180), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_knowledge_chunk_document_index')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_knowledge_point_id'), ['knowledge_point_id'], unique=False)

    op.create_table('knowledge_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('source_knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('target_knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=30), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('evidence_chunk_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("relation_type IN ('prerequisite','related_to','belongs_to','confused_with','applied_to')", name='ck_knowledge_relation_type'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_chunk_id'], ['knowledge_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_knowledge_point_id', 'target_knowledge_point_id', 'relation_type', name='uq_knowledge_relation_edge')
    )
    with op.batch_alter_table('knowledge_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_relations_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_relations_source_knowledge_point_id'), ['source_knowledge_point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_relations_target_knowledge_point_id'), ['target_knowledge_point_id'], unique=False)

    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('chapter_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('source_type', sa.String(length=30), nullable=False, server_default='legacy'))
        batch_op.add_column(sa.Column('processing_status', sa.String(length=30), nullable=False, server_default='parsed'))
        batch_op.add_column(sa.Column('page_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('metadata_json', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_knowledge_documents_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_course_id'), ['course_id'], unique=False)
        batch_op.create_unique_constraint('uq_knowledge_document_user_hash', ['user_id', 'content_hash'])
        batch_op.create_foreign_key('fk_knowledge_documents_course_id', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_knowledge_documents_chapter_id', 'chapters', ['chapter_id'], ['id'], ondelete='SET NULL')

    _backfill_legacy_documents()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_knowledge_documents_chapter_id', type_='foreignkey')
        batch_op.drop_constraint('fk_knowledge_documents_course_id', type_='foreignkey')
        batch_op.drop_constraint('uq_knowledge_document_user_hash', type_='unique')
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_course_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_content_hash'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_chapter_id'))
        batch_op.drop_column('metadata_json')
        batch_op.drop_column('content_hash')
        batch_op.drop_column('page_count')
        batch_op.drop_column('processing_status')
        batch_op.drop_column('source_type')
        batch_op.drop_column('source_filename')
        batch_op.drop_column('chapter_id')
        batch_op.drop_column('course_id')

    with op.batch_alter_table('knowledge_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_relations_target_knowledge_point_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_relations_source_knowledge_point_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_relations_course_id'))

    op.drop_table('knowledge_relations')
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_knowledge_point_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_document_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_course_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_content_hash'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_chapter_id'))

    op.drop_table('knowledge_chunks')
    with op.batch_alter_table('knowledge_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_points_course_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_points_chapter_id'))

    op.drop_table('knowledge_points')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapters_course_id'))

    op.drop_table('chapters')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_code'))

    op.drop_table('courses')
    # ### end Alembic commands ###


def _backfill_legacy_documents():
    """把旧 JSON chunks 迁移成可查询实体，不猜测页码、章节或知识点。"""
    bind = op.get_bind()
    documents = sa.table(
        'knowledge_documents',
        sa.column('id', sa.Integer),
        sa.column('user_id', sa.Integer),
        sa.column('title', sa.String),
        sa.column('content', sa.Text),
        sa.column('chunks', sa.JSON),
        sa.column('source_filename', sa.String),
        sa.column('source_type', sa.String),
        sa.column('processing_status', sa.String),
        sa.column('page_count', sa.Integer),
        sa.column('content_hash', sa.String),
        sa.column('metadata_json', sa.JSON),
    )
    knowledge_chunks = sa.table(
        'knowledge_chunks',
        sa.column('document_id', sa.Integer),
        sa.column('chunk_index', sa.Integer),
        sa.column('chunk_text', sa.Text),
        sa.column('content_hash', sa.String),
        sa.column('metadata_json', sa.JSON),
        sa.column('created_at', sa.DateTime),
    )

    rows = bind.execute(
        sa.select(
            documents.c.id,
            documents.c.user_id,
            documents.c.title,
            documents.c.content,
            documents.c.chunks,
        )
    ).mappings().all()
    seen_document_hashes = set()

    for row in rows:
        content = row['content'] or ''
        document_hash = hashlib.sha256(content.encode('utf-8')).hexdigest() if content else None
        unique_key = (row['user_id'], document_hash)
        if not document_hash or unique_key in seen_document_hashes:
            document_hash = None
        else:
            seen_document_hashes.add(unique_key)

        bind.execute(
            documents.update()
            .where(documents.c.id == row['id'])
            .values(
                source_filename=row['title'] or '',
                source_type='legacy',
                processing_status='parsed',
                page_count=0,
                content_hash=document_hash,
                metadata_json={'legacy': True, 'page_metadata_available': False},
            )
        )

        raw_chunks = row['chunks'] or []
        if isinstance(raw_chunks, str):
            try:
                raw_chunks = json.loads(raw_chunks)
            except (TypeError, ValueError):
                raw_chunks = []
        inserts = []
        for index, chunk_text in enumerate(raw_chunks):
            if not isinstance(chunk_text, str) or not chunk_text.strip():
                continue
            clean_chunk = chunk_text.strip()
            inserts.append({
                'document_id': row['id'],
                'chunk_index': index,
                'chunk_text': clean_chunk,
                'content_hash': hashlib.sha256(clean_chunk.encode('utf-8')).hexdigest(),
                'metadata_json': {'legacy': True, 'page_metadata_available': False},
                'created_at': datetime.now(),
            })
        if inserts:
            bind.execute(knowledge_chunks.insert(), inserts)
