"""baseline existing schema

Revision ID: 900e17ba0f92
Revises: 
Create Date: 2026-07-29 21:06:04.680735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900e17ba0f92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('chat_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('doc_type', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_documents_user_id'), ['user_id'], unique=False)

    op.create_table('learning_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_paths_user_id'), ['user_id'], unique=False)

    op.create_table('ppt_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('template_id', sa.String(length=120), nullable=True),
    sa.Column('remote_url', sa.Text(), nullable=True),
    sa.Column('local_url', sa.Text(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ppt_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ppt_records_sid'), ['sid'], unique=False)
        batch_op.create_index(batch_op.f('ix_ppt_records_user_id'), ['user_id'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=180), nullable=True),
    sa.Column('major', sa.String(length=120), nullable=True),
    sa.Column('knowledge_level', sa.String(length=80), nullable=True),
    sa.Column('learning_goal', sa.Text(), nullable=True),
    sa.Column('learning_style', sa.String(length=80), nullable=True),
    sa.Column('cognitive_preference', sa.String(length=120), nullable=True),
    sa.Column('prior_experience', sa.Text(), nullable=True),
    sa.Column('time_availability', sa.String(length=120), nullable=True),
    sa.Column('motivation_driver', sa.String(length=120), nullable=True),
    sa.Column('engagement_pattern', sa.String(length=120), nullable=True),
    sa.Column('weak_points', sa.Text(), nullable=True),
    sa.Column('raw_dialogue', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('quiz_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_content', sa.Text(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('wrong_questions', sa.Text(), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_results_user_id'), ['user_id'], unique=False)

    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_user_id'), ['user_id'], unique=False)

    op.create_table('task_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_action_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_action_logs_user_id'), ['user_id'], unique=False)

    op.create_table('coding_case_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('case_content', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('reference_answer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coding_case_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coding_case_records_user_id'), ['user_id'], unique=False)

    op.create_table('ppt_innovation_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ppt_record_id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('generated_by', sa.String(length=120), nullable=True),
    sa.Column('evaluation', sa.JSON(), nullable=True),
    sa.Column('basis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ppt_record_id'], ['ppt_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ppt_record_id', name='uq_ppt_innovation_analysis_record')
    )
    with op.batch_alter_table('ppt_innovation_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ppt_innovation_analyses_ppt_record_id'), ['ppt_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ppt_innovation_analyses_sid'), ['sid'], unique=False)
        batch_op.create_index(batch_op.f('ix_ppt_innovation_analyses_user_id'), ['user_id'], unique=False)

    op.create_table('resource_innovation_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('generated_by', sa.String(length=120), nullable=True),
    sa.Column('evaluation', sa.JSON(), nullable=True),
    sa.Column('basis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', name='uq_resource_innovation_analysis_resource')
    )
    with op.batch_alter_table('resource_innovation_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_innovation_analyses_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_innovation_analyses_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_innovation_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_innovation_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_resource_innovation_analyses_resource_id'))

    op.drop_table('resource_innovation_analyses')
    with op.batch_alter_table('ppt_innovation_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ppt_innovation_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_ppt_innovation_analyses_sid'))
        batch_op.drop_index(batch_op.f('ix_ppt_innovation_analyses_ppt_record_id'))

    op.drop_table('ppt_innovation_analyses')
    with op.batch_alter_table('coding_case_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coding_case_records_user_id'))

    op.drop_table('coding_case_records')
    with op.batch_alter_table('task_action_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_action_logs_user_id'))

    op.drop_table('task_action_logs')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_user_id'))

    op.drop_table('resources')
    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_results_user_id'))

    op.drop_table('quiz_results')
    op.drop_table('profiles')
    with op.batch_alter_table('ppt_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ppt_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_ppt_records_sid'))

    op.drop_table('ppt_records')
    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_paths_user_id'))

    op.drop_table('learning_paths')
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_user_id'))

    op.drop_table('knowledge_documents')
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_conversations_user_id'))

    op.drop_table('chat_conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
